
version: '3'

services:

    # PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        #image: adv-backend-task
        container_name: adv-backend-task
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
        networks:
            - app-network

    # MySQL Service
    database:
        image: mysql:5.7.22
        container_name: database
        restart: unless-stopped
        tty: true
        ports:
            - "4306:3306"
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_DATABASE: adv-db
            MYSQL_ROOT_PASSWORD: 1111
            MYSQL_PASSWORD: 1111
            MYSQL_USER: root
        networks:
            - app-network
            - mysql-phpmyadmin
    ####################################################################################################
    # PHPMyAdmin
    ####################################################################################################
    phpmyadmin:
        depends_on:
            - database
        image: phpmyadmin
        restart: always
        ports:
            - "8090:80"
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: password
        networks:
            - mysql-phpmyadmin
    # Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx:/etc/nginx/conf.d
        networks:
            - app-network

# Networks Configuration
networks:
    app-network:
        driver: bridge
    mysql-phpmyadmin:
volumes:
    db_data:
